### ISSUE TITLE
Teclado não fecha automaticamente

### ISSUE THREAD

**Issue by sosolidkk** [ES2-UFPI/Unichat#107]
# Bug
Ao selecionar o picker na tela de criação de perfil, o teclado não fecha, continua aberto.

# Passos para reprodução
1. Criar uma conta
2. Na tela de edição de perfil, inserir os dados
3. Ao mudar de e-mail para o picker o teclado continua aberto, o que não deveria ocorrer

**Comment by Mex978** [comment]
Com relação a isso, no caso eu consegui fazer pra que quando o usuário seleciona a linguagem no picker, o teclado desce. Pode deixar assim?

**Comment by sosolidkk** [comment]
> Com relação a isso, no caso eu consegui fazer pra que quando o usuário seleciona a linguagem no picker, o teclado desce. Pode deixar assim?

TIpo, o ideal seria na hora que o cara clicasse no picker pra **selecionar** a língua ele descesse, não após ter selecionado. Entendeu?
