### ISSUE TITLE
Não apagando mensagem após envio

### ISSUE THREAD

**Issue by sosolidkk** [ES2-UFPI/Unichat#117]
# Bug
Ao digitar uma mensagem e clicar para enviar, ocorrer casos que ela não some caso o usuário digite algo por acidente ou propositalmente.

# Passos para reprodução
1. Usuário digita uma mensagem
2. Usuário clica em enviar
3. Rapidamente, o usuário digita algo no mesmo TextInput da mensagem anteriormente digitada
4. A mensagem anterior é enviada, porém seu conteúdo permanece no TextInput com a adição do que foi digitado no passo 3

**Comment by Mex978** [comment]
Vou fazer
