### ISSUE TITLE
Fontes Responsíveis - Manter padronização em todos os dispositivos

### ISSUE THREAD

**Issue by mrvan04** [ES2-UFPI/Unichat#168]
Em alguns dispositivos a fonte fica muito pequena enquanto que em outros fica muito grande, estudar alguma forma de fontes responsivas para implementar.

**Comment by Mex978** [comment]
Posso resolver essa issue utilizando o módulo [react-native-responsive-fontSize](https://github.com/heyman333/react-native-responsive-fontSize)
Respondam se concordarem!

**Comment by netochaves** [comment]
No projeto existe uma lib já `react-native-size-matters` que acho que foi você até que instalou pra usar no componente `mensagem`, acho que o problema da pra ser resolvido com ela.
