### ISSUE TITLE
Criar função que recupera mensagem original do servidor

### ISSUE THREAD

**Issue by Mex978** [ES2-UFPI/Unichat#56]
A função a ser criada deve permitir que através do ID da mensagem selecionada para mostrar a linguagem original, o atributo no firebase que contém a mensagem em sua lingua original (de envio) seja recuperado para ser usado posteriormente ao atualizar no componente.

**Comment by sosolidkk** [comment]
Fechando essa issue devido a funcionalidade ter sido implementada junto de outra passada.
